### ISSUE TITLE
2.md - explain how to edit

### ISSUE THREAD

**Issue by lmalhoit** [CiscoDevNet/apic-em-learning-labs#10]
Just wanted to make it very clear that these files need to be edited from notepad or whatever editor and then saved.

Under Generate a Service Ticket change to:
2. If you’re using an alternate APIC-EM instead of the default one, edit the `username` and `password` parameter values and then save the edited document. Make sure to comment out the correct lines
#### To edit the code with a PC use Explorer to open the text file or use the `notepad` command followed by the file name from the CLI.

**Comment by annegentle** [comment]
Fixed.
