### ISSUE TITLE
2.md - parsing the Service Ticket

### ISSUE THREAD

**Issue by lmalhoit** [CiscoDevNet/apic-em-learning-labs#11]
I'm taking this part out because it's confusing, doesn't work, and isn't really necessary. 

To extract the service ticket value programmatically, use the following code to parse the response:

response_json = r.json()
print ("ticket: ",response_json["response"]["serviceTicket"])
The output from the preceding code looks similar to this:

ticket:  ST-16302-cKDpKVcv0fek6nx5YeaT-cas

**Comment by annegentle** [comment]
Fixed.
