### ISSUE TITLE
3.md - Task 2 is misleading, task 2 and 3 should be put together.

### ISSUE THREAD

**Issue by lmalhoit** [CiscoDevNet/apic-em-learning-labs#15]
Task 2 needs to be more clear that we run the script lab2-2-get-network-device-id-config.py

**Comment by lmalhoit** [comment]
I was mistaken, task 2 isn't really a task. It's just showing the code to run for task 3. So, I'm combining those to make it a little more clear.

**Comment by annegentle** [comment]
Yep, got it.
